int main() {
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    for(int i = 0; i < 10; i++) i = i;
    return 0;
}
